import type { SuratItem } from "./types"

export const INITIAL_SURAT_LIST: SuratItem[] = [
  {
    id: "SRT-2026-001",
    nomorSurat: "102/KPU-SU/VI/2026",
    perihal: "Undangan Rapat Pleno Rekapitulasi Pemilih Berkelanjutan",
    jenis: "masuk",
    pengirim: "KPU RI Jakarta",
    penerima: "Ketua KPU Provinsi Sulut",
    tanggal: "2026-08-01",
    prioritas: "sangat_penting",
    status: "menunggu_disposisi",
    fileName: "Surat_Undangan_Pleno_KPU_RI.pdf",
    fileSize: "1.4 MB",
    ringkasanIsi: "Pelaksanaan Rapat Pleno Rekapitulasi Data Pemilih Berkelanjutan Semester I Tahun 2026 secara virtual.",
    history: [
      {
        id: "h1",
        tanggal: "2026-08-01",
        waktu: "09:15 WITA",
        aktor: "Budi Santoso, S.Kom",
        jabatan: "Staf Agenda Persuratan",
        aksi: "Registrasi Surat Masuk",
        keterangan: "Input berkas fisik & pengunggahan scan PDF ke sistem.",
        badgeColor: "blue",
      },
    ],
  },
  {
    id: "SRT-2026-002",
    nomorSurat: "045/BAWASLU-SU/VIII/2026",
    perihal: "Permohonan Data Koordinasi Pengawasan Logistik Pilkada",
    jenis: "masuk",
    pengirim: "Bawaslu Provinsi Sulut",
    penerima: "Sekretaris KPU Provinsi Sulut",
    tanggal: "2026-08-04",
    prioritas: "penting",
    status: "dalam_proses",
    fileName: "Surat_Bawaslu_Logistik.pdf",
    fileSize: "890 KB",
    ringkasanIsi: "Permohonan daftar spesifikasi teknis dan jadwal gudang logistik Pemilu Kab/Kota.",
    disposisi: {
      tujuanUnit: "UMLOG (Umum dan Logistik)",
      catatan: "Segera siapkan matrik data gudang dan koordinasikan dengan PPK setempat.",
      prioritas: "penting",
      tenggatWaktu: "2026-08-12",
      tanggalDisposisi: "2026-08-05",
      disposisiOleh: "Drs. Meidy Tinangon, M.Si (Ketua KPU)",
    },
    history: [
      {
        id: "h1",
        tanggal: "2026-08-04",
        waktu: "14:20 WITA",
        aktor: "Siti Rahma",
        jabatan: "Arsiparis",
        aksi: "Registrasi Surat Masuk",
        keterangan: "Surat masuk diterima via email resmi KPU Sulut.",
      },
      {
        id: "h2",
        tanggal: "2026-08-05",
        waktu: "10:00 WITA",
        aktor: "Drs. Meidy Tinangon, M.Si",
        jabatan: "Ketua KPU Provinsi",
        aksi: "Perekaman Disposisi",
        keterangan: "Disposisi ke UMLOG (Umum dan Logistik) dengan catatan prioritas penting.",
      },
      {
        id: "h3",
        tanggal: "2026-08-05",
        waktu: "11:30 WITA",
        aktor: "Kasubag Logistik",
        jabatan: "Kasubag Logistik",
        aksi: "Proses Tindak Lanjut",
        keterangan: "Mulai penyusunan draft balasan & penyiapan tabel logistik.",
      },
    ],
  },
  {
    id: "SRT-2026-003",
    nomorSurat: "088/KPU-PROV/VIII/2026",
    perihal: "Surat Edaran Pelaksanaan Evaluasi Sistem Informasi Anggaran",
    jenis: "keluar",
    pengirim: "RENDATIN (Perencanaan, Data dan Informasi)",
    penerima: "KPU Kabupaten / Kota se-Sulawesi Utara",
    tanggal: "2026-08-07",
    prioritas: "biasa",
    status: "draft",
    fileName: "Draft_SE_Evaluasi_Anggaran.docx",
    ringkasanIsi: "Instruksi penyampaian laporan pelaksanaan anggaran triwulan II.",
    history: [
      {
        id: "h1",
        tanggal: "2026-08-07",
        waktu: "11:00 WITA",
        aktor: "Rian Pratama",
        jabatan: "Konseptor Surat",
        aksi: "Buat Draft Surat Keluar",
        keterangan: "Konsep awal diajukan ke Kasubag untuk verifikasi.",
      },
    ],
  },
  {
    id: "SRT-2026-004",
    nomorSurat: "092/KPU-PROV/VIII/2026",
    perihal: "Permohonan Narasumber Sosialisasi Keterbukaan Informasi",
    jenis: "keluar",
    pengirim: "Teknis Penyelenggaraan Pemilu",
    penerima: "Dinas Kominfo Provinsi Sulut",
    tanggal: "2026-08-08",
    prioritas: "penting",
    status: "menunggu_tte",
    fileName: "Draft_Surat_Permohonan_Narasumber.pdf",
    fileSize: "620 KB",
    ringkasanIsi: "Permohonan ketersediaan Kepala Dinas Kominfo menjadi pembicara web seminar KPU.",
    history: [
      {
        id: "h1",
        tanggal: "2026-08-08",
        waktu: "08:30 WITA",
        aktor: "Andi Wijaya",
        jabatan: "Konseptor Surat",
        aksi: "Buat Draft Surat Keluar",
        keterangan: "Draft dibuat dan diajukan ke pimpinan.",
      },
      {
        id: "h2",
        tanggal: "2026-08-08",
        waktu: "13:15 WITA",
        aktor: "Dr. Salman S., M.Si",
        jabatan: "Sekretaris KPU Provinsi",
        aksi: "Verifikasi / Approval Draft",
        keterangan: "Draft disetujui. Nomor registrasi otomatis diterbitkan: 092/KPU-PROV/VIII/2026. Lanjut ke Otorisasi TTE.",
      },
    ],
  },
  {
    id: "SRT-2026-005",
    nomorSurat: "079/KPU-PROV/VII/2026",
    perihal: "Penyampaian Laporan Keuangan Bulanan Juli 2026",
    jenis: "keluar",
    pengirim: "Sekretaris KPU Provinsi",
    penerima: "KPU RI / Biro Keuangan",
    tanggal: "2026-07-31",
    prioritas: "penting",
    status: "terkirim_terarsip",
    fileName: "Surat_Laporan_Keuangan_Juli2026_Signed.pdf",
    fileSize: "2.8 MB",
    ringkasanIsi: "Laporan pertanggungjawaban realisasi keuangan bulan Juli 2026 KPU Sulut.",
    tteInfo: {
      penandatangan: "Drs. Meidy Tinangon, M.Si",
      jabatan: "Ketua KPU Provinsi Sulawesi Utara",
      tanggalTte: "2026-07-31 16:45 WITA",
      barcodeData: "KPU-SULUT-TTE-20260731-079",
    },
    pengiriman: {
      metode: "email",
      tanggalKirim: "2026-07-31 17:00 WITA",
      nomorResiAtauBukti: "OUT-MAIL-20260731-8842",
    },
    history: [
      {
        id: "h1",
        tanggal: "2026-07-30",
        waktu: "10:00 WITA",
        aktor: "Staf Keuangan",
        jabatan: "Konseptor Surat",
        aksi: "Buat Draft Surat Keluar",
        keterangan: "Draft laporan keuangan disiapkan.",
      },
      {
        id: "h2",
        tanggal: "2026-07-31",
        waktu: "14:00 WITA",
        aktor: "Kabag KUL",
        jabatan: "Verifikator",
        aksi: "Verifikasi / Approval Draft",
        keterangan: "Disetujui tanpa revisi.",
      },
      {
        id: "h3",
        tanggal: "2026-07-31",
        waktu: "16:45 WITA",
        aktor: "Drs. Meidy Tinangon, M.Si",
        jabatan: "Ketua KPU",
        aksi: "Otorisasi Tanda Tangan (TTE)",
        keterangan: "Tanda tangan digital BSrE berhasil dibubuhkan.",
      },
      {
        id: "h4",
        tanggal: "2026-07-31",
        waktu: "17:00 WITA",
        aktor: "Sistem Otomatis",
        jabatan: "System Gateway",
        aksi: "Pengiriman & Distribusi",
        keterangan: "Email terkirim ke Biro Keuangan KPU RI. Status otomatis Terkirim & Terarsip.",
      },
    ],
  },
  {
    id: "SRT-2026-006",
    nomorSurat: "DRAFT-REV-012",
    perihal: "Nota Dinas Pengajuan Anggaran Bimbingan Teknis PPK",
    jenis: "nota_dinas",
    pengirim: "Teknis Penyelenggaraan Pemilu",
    penerima: "UMLOG (Umum dan Logistik)",
    tanggal: "2026-08-09",
    prioritas: "penting",
    status: "revisi",
    catatanRevisi: "Tolong perbaiki rincian anggaran konsumsi untuk H-1 pelaksanaan, sesuaikan dengan SBM 2026.",
    fileName: "Draft_ND_Bimtek_PPK.docx",
    ringkasanIsi: "Pengajuan rincian Kebutuhan operasional Bimtek Penyelenggara Pemilu Adhoc.",
    history: [
      {
        id: "h1",
        tanggal: "2026-08-09",
        waktu: "09:00 WITA",
        aktor: "Staf Teknis",
        jabatan: "Konseptor Surat",
        aksi: "Buat Draft Surat Keluar",
        keterangan: "Nota Dinas diajukan.",
      },
      {
        id: "h2",
        tanggal: "2026-08-09",
        waktu: "15:30 WITA",
        aktor: "Kabag KUL",
        jabatan: "Pejabat Penyetuju",
        aksi: "Verifikasi / Approval Draft",
        keterangan: "Perlu Revisi. Catatan: Sesuaikan tarif SBM 2026.",
      },
    ],
  },
]
