import { useState, useRef, useEffect } from "react"
import { MessageSquare, Send, Bot, User, Minimize2, Download, FileText, Loader2, Sparkles } from "lucide-react"
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "../ui/card"
import { Button } from "../ui/button"
import { Input } from "../ui/input"
import { ScrollArea } from "../ui/scroll-area"
import { Avatar, AvatarFallback } from "../ui/avatar"

export interface GeneratedFile {
  name: string
  content: string
  mimeType: string
  sizeStr: string
}

export interface ChatMessage {
  id: string
  sender: "user" | "bot"
  text: string
  timestamp: string
  fileAttachment?: GeneratedFile
}

export function KiranaChatbot({ theme = "light" }: { theme?: "light" | "dark" }) {
  const [isOpen, setIsOpen] = useState(false)
  const [inputMessage, setInputMessage] = useState("")
  const [isProcessing, setIsProcessing] = useState(false)

  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "1",
      sender: "bot",
      text: "Halo! Saya KIRANA Agent, Asisten AI Sistem Informasi KPU Sulut. Silakan ketik perintah atau klik salah satu Chip Cepat di bawah ini untuk membuat dokumen & laporan otomatis.",
      timestamp: "09:00",
    },
  ])

  const scrollRef = useRef<HTMLDivElement>(null)
  const isDark = theme === "dark"

  const quickChips = [
    "Surat Dinas",
    "Nota Dinas",
    "Lap. Anggaran",
    "Rekap Surat",
    "Jadwal"
  ]

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages, isOpen, isProcessing])

  // Pattern matching logic for agent processing
  const processAgent = (query: string): { reply: string; fileAttachment?: GeneratedFile } => {
    const lower = query.toLowerCase()

    if (lower.includes("surat dinas") || lower.includes("surat_dinas")) {
      const fileContent = `KPU PROVINSI SULAWESI UTARA
Jl. Diponegoro No. 12, Manado
--------------------------------------------------
SURAT DINAS
Nomor : 045/SD/KPU-SULUT/VIII/2026
Lamp. : 1 Berkas
Hal   : Koordinasi Logistik Pilkada Sulut 2026

Kepada Yth.
Ketua KPU Kabupaten/Kota se-Sulawesi Utara

Dengan hormat,
Sehubungan dengan pelaksanaan tahapan Pilkada 2026, bersama ini disampaikan jadwal verifikasi dan distribusi logistik ke daerah masing-masing.

Dimohon seluruh Ketua KPU Kab/Kota menugaskan UMLOG (Umum dan Logistik) untuk hadir pada:
Hari/Tanggal : Senin, 10 Agustus 2026
Waktu        : 09.00 WITA - Selesai
Tempat       : Aula KPU Provinsi Sulut

Demikian surat dinas ini disampaikan untuk dilaksanakan sebagaimana mestinya.

Manado, 6 Agustus 2026
Ketua KPU Provinsi Sulawesi Utara

[DRAFT GENERATED BY KIRANA AGENT]`

      return {
        reply: "Tentu! KIRANA telah menyusun draf Surat Dinas Koordinasi Logistik Pilkada 2026. Anda dapat mengunduh berkas lengkapnya di bawah ini.",
        fileAttachment: {
          name: "Surat_Dinas_KPU_Sulut_045.txt",
          content: fileContent,
          mimeType: "text/plain",
          sizeStr: "1.2 KB",
        },
      }
    }

    if (lower.includes("nota dinas") || lower.includes("nota_dinas")) {
      const fileContent = `KPU PROVINSI SULAWESI UTARA
==================================================
NOTA DINAS
Nomor: ND-102/KPU-SULUT/SUBBAG-TEKNIS/2026

Kepada Yth : Sekretaris KPU Provinsi Sulawesi Utara
Dari       : Kasubbag Teknis Penyelenggaraan
Tanggal    : 6 Agustus 2026
Sifat      : Penting
Perihal    : Pengajuan Kebutuhan Alat Tulis & Sistem Informasi Rapat Pleno

Sehubungan dengan persiapan Rapat Pleno Terbuka Rekapitulasi Pemilih, dengan ini diajukan dukungan sarana penunjang operasional berupa unit pengolahan data dan ruang server backup.

Demikian Nota Dinas ini kami sampaikan. Mohon petunjuk lebih lanjut.`

      return {
        reply: "Berikut draf Nota Dinas Pengajuan Sarana Rapat Pleno yang dibuat oleh KIRANA Agent. Silakan unduh dokumen untuk keperluan internal.",
        fileAttachment: {
          name: "Nota_Dinas_Subbag_Teknis.txt",
          content: fileContent,
          mimeType: "text/plain",
          sizeStr: "0.8 KB",
        },
      }
    }

    if (lower.includes("lap. anggaran") || lower.includes("laporan anggaran") || lower.includes("anggaran")) {
      const csvContent = `Kode_PA,Program_Anggaran,Pagu_PTP,Realisasi_Bulan_Ini,Sisa_Anggaran,Persentase
001,Honorarium Panitia Pemilihan,750000000,520000000,230000000,69.3%
002,Pengadaan Logistik & Kotak Suara,1200000000,980000000,220000000,81.6%
003,Sosialisasi & Edukasi Pemilih,450000000,310000000,140000000,68.8%
004,Sistem Informasi & Infrastruktur PTP,300000000,245000000,55000000,81.6%
TOTAL,,2700000000,2055000000,645000000,76.1%`

      return {
        reply: "Berikut Ringkasan Laporan Rekapitulasi Realisasi Anggaran PTP-KPU Sulut Tahun 2026. Berkas format CSV siap diunduh.",
        fileAttachment: {
          name: "Laporan_Realisasi_Anggaran_KPU_2026.csv",
          content: csvContent,
          mimeType: "text/csv",
          sizeStr: "2.4 KB",
        },
      }
    }

    if (lower.includes("rekap surat") || lower.includes("rekap_surat")) {
      const csvContent = `No_Surat,Tanggal,Pengirim,Perihal,Status,Kategori
001/KPU-SU/VI/2026,20 Jun 2026,Ketua KPU Provinsi,Undangan Rapat Pleno DPT,terkirim,Surat Keluar
002/KPU-SU/VI/2026,19 Jun 2026,KPU Kab. Minahasa,Laporan DPT Minahasa 2026,diterima,Surat Masuk
003/KPU-SU/VI/2026,18 Jun 2026,Bawaslu Sulut,Klarifikasi Data Pemilih,diproses,Surat Masuk
004/KPU-SU/VI/2026,17 Jun 2026,Subbagian Logistik,Nota Dinas Pengadaan Logistik,draft,Internal`

      return {
        reply: "KIRANA telah merekapitulasi seluruh daftar Surat Masuk & Keluar terbaru dalam file CSV berikut.",
        fileAttachment: {
          name: "Rekapitulasi_Surat_Menyurat_2026.csv",
          content: csvContent,
          mimeType: "text/csv",
          sizeStr: "1.8 KB",
        },
      }
    }

    if (lower.includes("jadwal") || lower.includes("agenda")) {
      const fileContent = `JADWAL TAHAPAN & AGENDA KPU PROVINSI SULUT (AGUSTUS 2026)
============================================================
1. 08 Agustus 2026 - Rapat Koordinasi Teknis Penyelenggaraan Pilkada (Aula KPU)
2. 12 Agustus 2026 - Batas Akhir Penyerahan Perbaikan Berkas DPT Kab/Kota
3. 15 Agustus 2026 - Pleno Terbuka Penetapan DPT Tingkat Provinsi
4. 20 Agustus 2026 - Simulasi Pemungutan & Penghitungan Suara Digital PTP
5. 25 Agustus 2026 - Bimbingan Teknis Petugas KPPS & PPK`

      return {
        reply: "Berikut jadwal lengkap tahapan agenda kegiatan KPU Sulawesi Utara untuk bulan Agustus 2026.",
        fileAttachment: {
          name: "Jadwal_Agenda_KPU_Sulut_Agustus_2026.txt",
          content: fileContent,
          mimeType: "text/plain",
          sizeStr: "0.9 KB",
        },
      }
    }

    if (lower.includes("arsip") || lower.includes("dokumen")) {
      const fileContent = `DAFTAR ARSIP DOKUMEN SISTEM INFORMASI KPU SULUT
------------------------------------------------
1. ARSIP-2026-001: SK Penetapan Tahapan Pilkada Sulut
2. ARSIP-2026-002: Berita Acara Rapat Pleno DPT Minahasa & Sangihe
3. ARSIP-2026-003: Draf MOU Kerjasama Media Massa & Sosialisasi
4. ARSIP-2026-004: Laporan Audit Keuangan Operasional Tahunan`

      return {
        reply: "Daftar berkas Arsip Dokumen KPU Sulut telah dikompilasi oleh KIRANA Agent.",
        fileAttachment: {
          name: "Daftar_Arsip_KPU_2026.txt",
          content: fileContent,
          mimeType: "text/plain",
          sizeStr: "0.7 KB",
        },
      }
    }

    // Default unrecognized reply
    return {
      reply: "Maaf, perintah belum dikenali oleh KIRANA Agent. Silakan pilih salah satu Chip Cepat di atas seperti [Surat Dinas], [Nota Dinas], [Lap. Anggaran], [Rekap Surat], atau [Jadwal] agar KIRANA dapat langsung memprosesnya.",
    }
  }

  const handleSendMessageText = (userText: string) => {
    if (!userText.trim() || isProcessing) return

    const now = new Date()
    const timeStr = `${now.getHours().toString().padStart(2, "0")}:${now
      .getMinutes()
      .toString()
      .padStart(2, "0")}`

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      sender: "user",
      text: userText,
      timestamp: timeStr,
    }

    setMessages((prev) => [...prev, userMsg])
    setInputMessage("")
    setIsProcessing(true)

    // Simulate Agent Processing Delay
    setTimeout(() => {
      const agentResult = processAgent(userText)

      const botMsg: ChatMessage = {
        id: (Date.now() + 1).toString(),
        sender: "bot",
        text: agentResult.reply,
        timestamp: timeStr,
        fileAttachment: agentResult.fileAttachment,
      }

      setMessages((prev) => [...prev, botMsg])
      setIsProcessing(false)
    }, 700)
  }

  const handleSubmit = (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    handleSendMessageText(inputMessage)
  }

  const handleDownloadFile = (file: GeneratedFile) => {
    const blob = new Blob([file.content], { type: file.mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = file.name
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed bottom-6 right-6 z-50">
      {isOpen ? (
        <Card
          className={`w-80 md:w-96 h-[520px] shadow-2xl flex flex-col backdrop-blur-md transition-all duration-200 animate-in fade-in slide-in-from-bottom-5 ${isDark
              ? "border-[#1e293b] bg-[#0c1220]/95 text-gray-100"
              : "border-slate-200 bg-white/95 text-slate-800 shadow-slate-300/60"
            }`}
        >
          {/* Header */}
          <CardHeader
            className={`p-3.5 border-b flex flex-row items-center justify-between shrink-0 ${isDark ? "border-[#1e293b] bg-[#11192b]" : "border-slate-200 bg-slate-50"
              }`}
          >
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-red-600/20 border border-red-500/40 flex items-center justify-center text-red-600 font-bold">
                <Bot className="w-4 h-4" />
              </div>
              <div>
                <CardTitle
                  className={`text-sm font-bold flex items-center gap-1.5 ${isDark ? "text-gray-100" : "text-slate-900"
                    }`}
                >
                  KIRANA Agent
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
                </CardTitle>
                <p className={`text-[10px] ${isDark ? "text-gray-400" : "text-slate-500"}`}>
                  AI Agent KPU Sulut | Standby
                </p>
              </div>
            </div>

            <div className="flex items-center gap-1">
              <button
                onClick={() => setIsOpen(false)}
                className={`p-1.5 rounded-lg transition-colors cursor-pointer ${isDark
                    ? "text-gray-400 hover:text-white hover:bg-[#1e293b]"
                    : "text-slate-400 hover:text-slate-800 hover:bg-slate-200"
                  }`}
                title="Perkecil Widget"
              >
                <Minimize2 className="w-4 h-4" />
              </button>
            </div>
          </CardHeader>

          {/* Quick Suggestions Chips Section */}
          <div
            className={`px-3 py-2 border-b flex items-center gap-1.5 overflow-x-auto custom-scrollbar shrink-0 ${isDark ? "bg-[#090e1a] border-[#1e293b]" : "bg-slate-100/70 border-slate-200"
              }`}
          >
            <span className="text-[10px] font-bold text-red-600 dark:text-red-400 shrink-0 flex items-center gap-1">
              <Sparkles className="w-3 h-3" /> Chip Cepat:
            </span>
            {quickChips.map((chip, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => handleSendMessageText(chip)}
                disabled={isProcessing}
                className={`px-2 py-0.5 rounded-full text-[10px] font-medium whitespace-nowrap transition-all cursor-pointer border shrink-0 ${isDark
                    ? "bg-[#131d30] border-[#1e293b] text-gray-300 hover:border-red-500 hover:text-white hover:bg-red-950/40"
                    : "bg-white border-slate-300 text-slate-700 hover:border-red-500 hover:text-red-600 hover:bg-red-50"
                  }`}
              >
                [{chip}]
              </button>
            ))}
          </div>

          {/* Messages Area */}
          <CardContent className="p-3 flex-1 overflow-hidden">
            <ScrollArea className="h-full pr-2" ref={scrollRef}>
              <div className="space-y-3">
                {messages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex items-start gap-2.5 ${msg.sender === "user" ? "flex-row-reverse" : "flex-row"
                      }`}
                  >
                    <Avatar className="w-7 h-7 shrink-0">
                      <AvatarFallback
                        className={
                          msg.sender === "user"
                            ? "bg-red-600 text-white text-[10px]"
                            : isDark
                              ? "bg-[#1e293b] text-red-400 text-[10px]"
                              : "bg-red-50 text-red-600 border border-red-200 text-[10px]"
                        }
                      >
                        {msg.sender === "user" ? <User className="w-3.5 h-3.5" /> : <Bot className="w-3.5 h-3.5" />}
                      </AvatarFallback>
                    </Avatar>

                    <div
                      className={`max-w-[82%] rounded-xl px-3 py-2 text-xs leading-relaxed ${msg.sender === "user"
                          ? "bg-red-600 text-white rounded-tr-none shadow-sm"
                          : isDark
                            ? "bg-[#162032] text-gray-200 border border-[#1e293b] rounded-tl-none shadow-sm"
                            : "bg-slate-100 text-slate-800 border border-slate-200 rounded-tl-none shadow-sm"
                        }`}
                    >
                      <p>{msg.text}</p>

                      {/* File Attachment Box & Download Button */}
                      {msg.fileAttachment && (
                        <div
                          className={`mt-2.5 p-2.5 rounded-lg border flex items-center justify-between gap-2 ${isDark
                              ? "bg-[#0b101c] border-red-500/30 text-gray-200"
                              : "bg-white border-red-200 text-slate-800 shadow-xs"
                            }`}
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <FileText className="w-4 h-4 text-red-500 shrink-0" />
                            <div className="min-w-0">
                              <p className="font-semibold text-[11px] truncate">{msg.fileAttachment.name}</p>
                              <span className="text-[9px] text-gray-400 block">{msg.fileAttachment.sizeStr}</span>
                            </div>
                          </div>
                          <button
                            type="button"
                            onClick={() => handleDownloadFile(msg.fileAttachment!)}
                            className="px-2.5 py-1 rounded bg-red-600 hover:bg-red-700 text-white text-[10px] font-semibold flex items-center gap-1 shrink-0 cursor-pointer shadow-xs transition-all"
                            title="Unduh file hasil generate"
                          >
                            <Download className="w-3 h-3" />
                            <span>Unduh</span>
                          </button>
                        </div>
                      )}

                      <span
                        className={`text-[9px] block mt-1 text-right ${msg.sender === "user" ? "text-red-100" : isDark ? "text-gray-400" : "text-slate-400"
                          }`}
                      >
                        {msg.timestamp}
                      </span>
                    </div>
                  </div>
                ))}

                {/* Processing Indicator */}
                {isProcessing && (
                  <div className="flex items-start gap-2.5">
                    <Avatar className="w-7 h-7 shrink-0">
                      <AvatarFallback
                        className={
                          isDark
                            ? "bg-[#1e293b] text-red-400 text-[10px]"
                            : "bg-red-50 text-red-600 border border-red-200 text-[10px]"
                        }
                      >
                        <Bot className="w-3.5 h-3.5" />
                      </AvatarFallback>
                    </Avatar>
                    <div
                      className={`rounded-xl px-3 py-2 text-xs flex items-center gap-2 italic ${isDark ? "bg-[#162032] text-red-400 border border-[#1e293b]" : "bg-red-50 text-red-600 border border-red-200"
                        }`}
                    >
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      <span>KIRANA sedang memproses...</span>
                    </div>
                  </div>
                )}
              </div>
            </ScrollArea>
          </CardContent>

          {/* Input Area */}
          <CardFooter
            className={`p-3 border-t shrink-0 ${isDark ? "border-[#1e293b] bg-[#0c1220]" : "border-slate-200 bg-white"
              }`}
          >
            <form onSubmit={handleSubmit} className="flex items-center gap-2 w-full">
              <Input
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                placeholder="Tulis pesan atau pilih chip..."
                disabled={isProcessing}
                className={`text-xs focus:border-red-500 ${isDark
                    ? "bg-[#131b2e] border-[#1e293b] text-gray-100 placeholder:text-gray-500"
                    : "bg-slate-50 border-slate-300 text-slate-900 placeholder:text-slate-400 focus:bg-white"
                  }`}
              />
              <Button
                type="submit"
                size="icon"
                disabled={isProcessing || !inputMessage.trim()}
                className="shrink-0 bg-red-600 hover:bg-red-700 text-white cursor-pointer"
              >
                <Send className="w-4 h-4" />
              </Button>
            </form>
          </CardFooter>
        </Card>
      ) : (
        <button
          onClick={() => setIsOpen(true)}
          className="relative group p-4 rounded-2xl btn-kpu-red text-white hover:scale-105 active:scale-95 transition-all duration-200 flex items-center justify-center cursor-pointer"
          title="Buka KIRANA Agent"
        >
          <MessageSquare className="w-6 h-6" />
          <span className="absolute -top-1 -right-1 w-4 h-4 bg-black text-white dark:bg-white dark:text-black rounded-full text-[9px] font-black flex items-center justify-center border border-white/20 shadow-xs">
            AI
          </span>
        </button>
      )}
    </div>
  )
}
